# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36fdbbb39c313290f63ddb0cbfae9c82361fc68306d02cd2fb2bf85bdeec7be80cad1f930cf82f4f3b71aaead7ea5e5bd78743d6de8276282fa84c22de2cdce4

test:
  secret_key_base: 5749424998adde70f2d43095fc7adf4485727f6f3b51c733261d48311e6ef6c444e90c844deab15d7609b2f5ca8e36e06c64240d0a00fb9f14aeed8cad7133d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
